trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    displayName: "DEV"
    variables:
      - group: estudosaks-dev
    jobs:
    - job: azureResources
      displayName: "Docker Build"
      steps:
        - task:
          - template: ../templates/template-docker-build.yaml
            parameters:
              serviceConnection: 'sc-estudos'
              containerRegistry: $(containerRegistry)
              acrLogin: $(acrLogin)

        - task: catAppDeploy
          displayName: "cat file"
          steps:
            - script: cat 01_kubernetes_aks/app-deploy.yaml 

        - task: azureResources2
          displayName: "Kubernets Build"
          steps:
          - template: ../templates/template-kubernets-build.yaml
            parameters:
              serviceConnection: 'sc-estudos'
              containerRegistry: $(containerRegistry)
              acrLogin: $(acrLogin)
