trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    displayName: "DEV"
    variables:
      - group: estudosaks-dev
    jobs:
    - job: azureResources
      displayName: "Docker Build"
      steps:
      - template: ../templates/template-docker-build.yaml
        parameters:
          serviceConnection: 'sc-estudos'
          containerRegistry: $(containerRegistry)
          acrLogin: $(acrLogin)

    - job: catAppDeploy
      displayName: "cat file"
      steps:
        - script: cat 01_kubernetes_aks/app-deploy.yaml 

    - job: azureResources
      displayName: "Kubernets Build"
      steps:
      - template: ../templates/template-kubernets-build.yaml
        parameters:
          serviceConnection: 'sc-estudos'
          containerRegistry: $(containerRegistry)
          acrLogin: $(acrLogin)
    